import { ReactNode } from 'react'
import './globals.css'
import { Roboto } from 'next/font/google'

const roboto400 = Roboto({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-roboto-400',
})
const roboto700 = Roboto({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-roboto-700',
})

export const metadata = {
  title: 'Ignite Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto400.variable} ${roboto700.variable}`}>
        {children}
      </body>
    </html>
  )
}
